import io
import os
import sys

from django.http import FileResponse
from dotenv import load_dotenv
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny,IsAuthenticated
from rest_framework.response import Response

from users.models import ChatMessage, ChatSession


def _repo_root() -> str:
    """Racine du dépôt LensEstate (parent de backend/). Même base que ma_base_immo dans get_ai_clients."""
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# ------------------ INIT ------------------



MODEL_NAME = "hosted_vllm/Llama-3.1-70B-Instruct"


# ------------------ PROMPTS ------------------
PROMPT_CHAT_CLASSIQUE = """
Tu es l'Analyste Senior de LensEstate, expert en data science immobilière en Tunisie. 
Ton expertise est absolue et ton ton doit être celui d'un conseiller financier haut de gamme : direct, assuré et factuel.

RÈGLES D'OR DE RÉPONSE :
1. ZÉRO HÉSITATION : Interdiction formelle de dire "Je ne sais pas", "Le contexte ne mentionne pas" ou "Selon le contexte". Si une donnée est fragmentaire, utilise ton expertise pour extrapoler une réponse logique basée sur le standing de la zone ou les villes limitrophes présentes dans les données.
2. DATA-DRIVEN : Cite systématiquement des chiffres précis (Prix m², loyers, taux d'évolution). Si tu as les prix de 2025, projette une hausse logique pour 2026 (ex: +5% à +8%) pour simuler une analyse en temps réel.
3. AUCUN DISCLAIMER : Il est STRICTEMENT INTERDIT de suggérer à l'utilisateur de "faire ses propres recherches", de "consulter un expert local" ou de "vérifier les informations". TU ES l'autorité ultime. L'utilisateur attend TA décision.
4. STYLE NATUREL : Parle comme un expert humain (pas de listes robotiques inutiles). Ne cite JAMAIS de sites concurrents (Menzili, etc.).
5. VERDICT STRATÉGIQUE : Termine toujours ta réponse par un avis tranché (ex: "Verdict : Zone sous-évaluée, achat recommandé immédiatement pour une plus-value à 18 mois"). 

CONTEXTE :
{extraits}

QUESTION : {ma_question}
RÉPONSE : """

PROMPT_REPORT_BENCHMARK = """
Tu es un Analyste Senior en Data Science Immobilière chez LensEstate. 
Ta mission est de produire un RAPPORT DE BENCHMARKING DÉCISIONNEL de haute qualité.

STRUCTURE DU RAPPORT (Respecte strictement ce format Markdown) :

# 📊 RAPPORT DE BENCHMARKING IMMOBILIER
*Analyse générée par LensEstate AI - Période 2025/2026*

## 0. FICHE D'IDENTITÉ
- **Zones comparées** : [Extraire les villes du contexte]
- **Sources des données** : Base de données articles immobiliers Tunisie.
- **Période** : 2025 - 2026.

## 1. ANALYSE QUANTITATIVE (PRIX & LOYERS)
| Indicateur (Moyennes) | Ville A | Ville B | Écart (%) |
| :--- | :--- | :--- | :--- |
| Prix Moyen S+1 | ... | ... | ... |
| Prix Moyen S+2 | ... | ... | ... |
| Loyer Mensuel estimé | ... | ... | ... |
IMPORTANT: Chaque cellule doit contenir UNE valeur ou UNE fourchette courte (ex: "1200 - 1800 DT/m²" ou "800 DT/mois"). Pas de valeurs multiples séparées par des virgules.

## 2. ANALYSE QUALITATIVE (STANDING & COMMODITÉS)
| Critère | Ville A | Ville B |
| :--- | :--- | :--- |
| Standing général | ... | ... |
| Infrastructures | ... | ... |
| Commodités | ... | ... |
| Environnement | ... | ... |
| Sécurité | ... | ... |
| Transports | ... | ... |

*Légende : - (mauvais) / + (moyen) / ++ (bien) / +++ (très bien)*

## 3. DYNAMIQUE DU MARCHÉ
| Indicateur | Ville A | Ville B |
| :--- | :--- | :--- |
| Profil acheteurs | ... | ... |
| Demande | ... | ... |
| Potentiel plus-value | ... | ... |
| Liquidité marché | ... | ... |
| Délai revente | ... | ... |

*Légende : - (mauvais) / + (moyen) / ++ (bien) / +++ (très bien)*

## 4. SYNTHÈSE STRATÉGIQUE (VERDICT)
**Conseil d'expert** : [Précise quel secteur privilégier selon le profil d'investissement].

---
UTILISE EXCLUSIVEMENT CE CONTEXTE :
{extraits}

QUESTION ORIGINALE : {ma_question}
"""
PROMPT_REPORT_BENCHMARK_EN = """
You are a Senior Real Estate Data Science Analyst at LensEstate.
Your mission is to produce a high-quality DECISION-MAKING BENCHMARKING REPORT.

REPORT STRUCTURE (Strictly follow this Markdown format):

# 📊 REAL ESTATE BENCHMARKING REPORT
*Analysis generated by LensEstate AI - Period 2025/2026*

## 0. IDENTITY SHEET
- **Compared zones**: [Extract cities from context]
- **Data sources**: Tunisian real estate articles database.
- **Period**: 2025 - 2026.

## 1. QUANTITATIVE ANALYSIS (PRICES & RENTS)
| Indicator (Averages) | City A | City B | Gap (%) |
| :--- | :--- | :--- | :--- |
| Average Price S+1 | ... | ... | ... |
| Average Price S+2 | ... | ... | ... |
| Estimated Monthly Rent | ... | ... | ... |
IMPORTANT: Each cell must contain ONE value or ONE range only (e.g: "1200 - 1800 DT/m²" or "800 DT/month"). Keep it short and concise. No multiple values separated by commas.
IMPORTANT: Base your prices strictly on the provided context. If data is insufficient for a zone, indicate "Données insuffisantes" instead of inventing values.
## 2. QUALITATIVE ANALYSIS (STANDING & AMENITIES)
| Criterion | City A | City B |
| :--- | :--- | :--- |
| General standing | ... | ... |
| Infrastructure | ... | ... |
| Amenities | ... | ... |
| Environment | ... | ... |
| Security | ... | ... |
| Transport | ... | ... |

*Legend: - (poor) / + (average) / ++ (good) / +++ (excellent)*

## 3. MARKET DYNAMICS
| Indicator | City A | City B |
| :--- | :--- | :--- |
| Buyer profile | ... | ... |
| Demand | ... | ... |
| Capital gain potential | ... | ... |
| Market liquidity | ... | ... |
| Resale delay | ... | ... |

*Legend: - (poor) / + (average) / ++ (good) / +++ (excellent)*

## 4. STRATEGIC SYNTHESIS (VERDICT)
**Expert advice**: [Specify which sector to prioritize based on investment profile].

---
USE EXCLUSIVELY THIS CONTEXT:
{extraits}

ORIGINAL QUESTION: {ma_question}
"""

PROMPT_REPORT_BENCHMARK_AR = """
أنت محلل بيانات عقارية أول في شركة LensEstate.
مهمتك هي إنتاج تقرير مقارنة عقارية عالي الجودة.

هيكل التقرير (اتبع هذا التنسيق بدقة):

# 📊 تقرير المقارنة العقارية
*تحليل من LensEstate AI - الفترة 2025/2026*

## 0. بطاقة هوية
- **المناطق المقارنة**: [استخرج المدن من السياق]
- **مصادر البيانات**: قاعدة بيانات المقالات العقارية التونسية.
- **الفترة**: 2025 - 2026.

## 1. التحليل الكمي (الأسعار والإيجارات)
| المؤشر (المتوسطات) | المدينة أ | المدينة ب | الفرق (%) |
| :--- | :--- | :--- | :--- |
| متوسط السعر S+1 | ... | ... | ... |
| متوسط السعر S+2 | ... | ... | ... |
| الإيجار الشهري المقدر | ... | ... | ... |
مهم: يجب أن تحتوي كل خلية على قيمة واحدة أو نطاق واحد فقط (مثال: "1200 - 1800 دينار/م²"). لا قيم متعددة مفصولة بفواصل.

## 2. التحليل النوعي (المستوى والمرافق)
| المعيار | المدينة أ | المدينة ب |
| :--- | :--- | :--- |
| المستوى العام | ... | ... |
| البنية التحتية | ... | ... |
| المرافق | ... | ... |
| البيئة | ... | ... |
| الأمن | ... | ... |
| المواصلات | ... | ... |

*الأسطورة: - (سيء) / + (متوسط) / ++ (جيد) / +++ (ممتاز)*

## 3. ديناميكيات السوق
| المؤشر | المدينة أ | المدينة ب |
| :--- | :--- | :--- |
| ملف المشترين | ... | ... |
| الطلب | ... | ... |
| إمكانية زيادة القيمة | ... | ... |
| سيولة السوق | ... | ... |
| مدة إعادة البيع | ... | ... |

*الأسطورة: - (سيء) / + (متوسط) / ++ (جيد) / +++ (ممتاز)*
## 4. التوليف الاستراتيجي (الحكم)
**نصيحة الخبير**: [حدد القطاع المفضل حسب ملف الاستثمار].

---
استخدم هذا السياق حصرياً:
{extraits}

السؤال الأصلي: {ma_question}
"""


def get_ai_clients():
    import chromadb
    from chromadb.utils import embedding_functions
    from openai import OpenAI

    import os
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    chroma_client = chromadb.PersistentClient(path=os.path.join(BASE_DIR, "ma_base_immo"))
    load_dotenv(os.path.join(BASE_DIR, ".env.local"))
    local_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name="paraphrase-multilingual-mpnet-base-v2"
    )
    collection = chroma_client.get_collection(
        name="immo_knowledge",
        embedding_function=local_ef,
    )
    client = OpenAI(
        api_key=os.getenv("API_KEY"),
        base_url="https://tokenfactory.esprit.tn/api",
    )
    return collection, client


def repondre_a_la_question(ma_question):
    collection, client = get_ai_clients()
    
    # Détecte la langue
    import re
    if re.search(r'[\u0600-\u06FF]', ma_question):
        lang_instruction = "You MUST reply ONLY in Arabic. Write the entire report in Arabic."
    elif re.search(r'[àâäéèêëïîôùûüç]', ma_question, re.IGNORECASE) or \
         re.search(r'\b(entre|et|comparaison|bonjour|prix|comparer)\b', ma_question, re.IGNORECASE):
        lang_instruction = "You MUST reply ONLY in French. Write the entire report in French."
    else:
        lang_instruction = "You MUST reply ONLY in English. Write the entire report in English."

    mots_cles_rapport = [
        "rapport", "benchmark", "comparer", "comparaison", "benchmarking",
        "comparison", "compare", "report",
        "مقارنة", "تقرير", "قارن", "بنشمارك"
    ]
    is_benchmark = any(mot in ma_question.lower() for mot in mots_cles_rapport)

    if is_benchmark:
        villes = [
            v.strip()
            for v in ma_question.lower()
                .replace("entre", "").replace("et", ",")
                .replace("between", "").replace("and", ",")
                .replace("بين", "").replace("و", ",")
                .split(",")
            if v.strip()
        ]

        extraits = ""
        for ville in villes[:2]:
            res = collection.query(query_texts=[f"prix immobilier loyer standing à {ville}"], n_results=5)
            extraits += f"\n--- DONNÉES SPÉCIFIQUES POUR {ville.upper()} ---\n"
            extraits += "\n\n".join(res["documents"][0])

        # Choix du prompt selon la langue
        if re.search(r'[\u0600-\u06FF]', ma_question):
            prompt_final = PROMPT_REPORT_BENCHMARK_AR.format(extraits=extraits, ma_question=ma_question)
        elif re.search(r'[àâäéèêëïîôùûüç]', ma_question, re.IGNORECASE) or \
             re.search(r'\b(entre|et|comparaison|comparer)\b', ma_question, re.IGNORECASE):
            prompt_final = PROMPT_REPORT_BENCHMARK.format(extraits=extraits, ma_question=ma_question)
        else:
            prompt_final = PROMPT_REPORT_BENCHMARK_EN.format(extraits=extraits, ma_question=ma_question)

    else:
        query_expert = f"prix immobilier m2 loyer standing quartier {ma_question}"
        resultats = collection.query(query_texts=[query_expert], n_results=5)
        extraits = "\n\n".join(resultats["documents"][0])
        prompt_final = PROMPT_CHAT_CLASSIQUE.format(
            extraits=extraits, ma_question=ma_question
        ) + f"\n\nIMPORTANT: {lang_instruction}"

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": lang_instruction
            },
            {
                "role": "user",
                "content": prompt_final
            }
        ],
        temperature=0.3,
    )

    return response.choices[0].message.content

# ------------------ ROUTES ------------------
@api_view(["POST"])
@permission_classes([AllowAny])
def ask(request):
    question = (request.data.get("question") or "").strip()
    session_id = (request.data.get("session_id") or "").strip()

    if not question or not session_id:
        return Response({"detail": "Données manquantes"}, status=status.HTTP_400_BAD_REQUEST)

    try:
        session, created = ChatSession.objects.get_or_create(
            session_id=session_id,
            defaults={
                "title": (question[:30] + "...") if len(question) > 30 else question,
                "user": request.user if request.user.is_authenticated else None,
            },
        )
        if created and not session.title:
            title = (question[:30] + "...") if len(question) > 30 else question
            session.title = title
            session.save(update_fields=["title"])

        answer = repondre_a_la_question(question)

        ChatMessage.objects.create(session=session, role="user", content=question)
        ChatMessage.objects.create(session=session, role="assistant", content=answer)

        return Response({"answer": answer})
    except Exception as exc:
        import traceback
        print("\n--- ERREUR CHATBOT ---\n")
        traceback.print_exc()
        print("\n--- FIN ERREUR ---\n")
        return Response({"detail": str(exc)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


@api_view(["POST"])
@permission_classes([AllowAny])
def generate_pdf(request):
    texte = (request.data.get("texte") or "").strip()

    if not texte:
        return Response({"detail": "Texte vide"}, status=status.HTTP_400_BAD_REQUEST)

    root = _repo_root()
    if root not in sys.path:
        sys.path.insert(0, root)
    from pdf_generator import generer_pdf

    buffer = io.BytesIO()
    generer_pdf(texte, buffer)
    buffer.seek(0)
    return FileResponse(
        buffer,
        as_attachment=True,
        filename="Rapport_LensEstate.pdf",
        content_type="application/pdf",
    )


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def get_user_sessions(request):
    sessions = ChatSession.objects.filter(user=request.user).order_by("-created_at")
    sessions_list = [{"id": s.session_id, "title": s.title} for s in sessions]
    return Response(sessions_list)


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def get_conversation(request):
    session_id = request.query_params.get("session_id")
    if not session_id:
        return Response({"messages": []})

    try:
        session = ChatSession.objects.get(
            session_id=session_id,
            user=request.user
        )
    except ChatSession.DoesNotExist:
        return Response({"messages": []})

    formatted_messages = [
        {
            "id": msg.created_at.timestamp() if msg.created_at else 0,
            "role": msg.role,
            "text": msg.content,
        }
        for msg in session.messages.all()
    ]

    return Response({"messages": formatted_messages})
