/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricePredictionRouteImport } from './routes/price-prediction'
import { Route as PlanGeneratorRouteImport } from './routes/plan-generator'
import { Route as MapRouteImport } from './routes/map'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'

const PricePredictionRoute = PricePredictionRouteImport.update({
  id: '/price-prediction',
  path: '/price-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanGeneratorRoute = PlanGeneratorRouteImport.update({
  id: '/plan-generator',
  path: '/plan-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRouteWithChildren
  '/forecasting': typeof ForecastingRoute
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/plan-generator': typeof PlanGeneratorRoute
  '/price-prediction': typeof PricePredictionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRouteWithChildren
  '/forecasting': typeof ForecastingRoute
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/plan-generator': typeof PlanGeneratorRoute
  '/price-prediction': typeof PricePredictionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRouteWithChildren
  '/forecasting': typeof ForecastingRoute
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/plan-generator': typeof PlanGeneratorRoute
  '/price-prediction': typeof PricePredictionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/forecasting'
    | '/listings'
    | '/map'
    | '/plan-generator'
    | '/price-prediction'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/forecasting'
    | '/listings'
    | '/map'
    | '/plan-generator'
    | '/price-prediction'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/forecasting'
    | '/listings'
    | '/map'
    | '/plan-generator'
    | '/price-prediction'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForecastingRoute: typeof ForecastingRoute
  ListingsRoute: typeof ListingsRoute
  MapRoute: typeof MapRoute
  PlanGeneratorRoute: typeof PlanGeneratorRoute
  PricePredictionRoute: typeof PricePredictionRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/price-prediction': {
      id: '/price-prediction'
      path: '/price-prediction'
      fullPath: '/price-prediction'
      preLoaderRoute: typeof PricePredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-generator': {
      id: '/plan-generator'
      path: '/plan-generator'
      fullPath: '/plan-generator'
      preLoaderRoute: typeof PlanGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRouteWithChildren,
  ForecastingRoute: ForecastingRoute,
  ListingsRoute: ListingsRoute,
  MapRoute: MapRoute,
  PlanGeneratorRoute: PlanGeneratorRoute,
  PricePredictionRoute: PricePredictionRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
