# Generated by Django 6.0.4 on 2026-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=100, unique=True)),
                ('listing_url', models.URLField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('transaction_type', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(default='TND', max_length=10)),
                ('surface_m2', models.FloatField(blank=True, null=True)),
                ('rooms', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(default='Tunisia', max_length=100)),
                ('governorate', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_word_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('has_images', models.BooleanField(default=False)),
                ('seller_type', models.CharField(blank=True, max_length=50)),
                ('is_agency', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_basement', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_furniture', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_standing', models.BooleanField(default=False)),
                ('has_terrace', models.BooleanField(default=False)),
                ('has_sea_view', models.BooleanField(default=False)),
                ('is_price_imputed', models.BooleanField(default=False)),
                ('has_surface', models.BooleanField(default=False)),
                ('has_rooms_info', models.BooleanField(default=False)),
                ('has_bathrooms_info', models.BooleanField(default=False)),
                ('has_bedrooms_info', models.BooleanField(default=False)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['governorate'], name='listings_li_governo_5b8d6a_idx'), models.Index(fields=['city'], name='listings_li_city_e45c53_idx'), models.Index(fields=['property_type'], name='listings_li_propert_7a505c_idx'), models.Index(fields=['transaction_type'], name='listings_li_transac_79321a_idx'), models.Index(fields=['price'], name='listings_li_price_d6caaa_idx')],
            },
        ),
    ]
